version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: fileshare-postgres
    restart: unless-stopped
    volumes:
      - fileshare-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_password

volumes:
  fileshare-postgres:
    driver: local