var c=Object.defineProperty;var d=(i,s,t)=>s in i?c(i,s,{enumerable:!0,configurable:!0,writable:!0,value:t}):i[s]=t;var e=(i,s,t)=>(d(i,typeof s!="symbol"?s+"":s,t),t);const m=`
<link rel="stylesheet" href="/static/css/fileshare.css">
<dialog id="form-modal">
	<article id="form-article">
		<a href="#" aria-label="Close" id="form-modal-close" class="close"></a>
		<h3>
			<slot name="title">Title</slot>
		</h3>
		<slot name="form">Form</slot>
	</article>
</dialog>
`;class l extends HTMLDialogElement{constructor(){super();e(this,"template");e(this,"content");e(this,"closeButton");e(this,"dialog");e(this,"article");e(this,"animateInOut",!1);e(this,"eventData");e(this,"visible",!1);e(this,"persistEventHandler",null);e(this,"titleSlotElement");e(this,"closeButtonListener",()=>{this.dispatchEvent(new CustomEvent("cancel",{detail:this.eventData})),this.closeModal()});e(this,"noPersistHandler",t=>{this.visible&&(this.article.contains(t.target)||this.closeModal())});this.template=document.createElement("template"),this.template.innerHTML=m,this.content=this.template.content;const t=this.attachShadow({mode:"open"});t.appendChild(this.content.cloneNode(!0)),this.closeButton=t.querySelector("#form-modal-close"),this.dialog=t.querySelector("#form-modal"),this.article=t.querySelector("#form-article"),this.titleSlotElement=t.querySelector("#form-modal-title")}static get observedAttributes(){return["animate","persist","confirm-button-class","cancel-button-class","event-data","title","message"]}closeModal(){if(!this.animateInOut){this.dialog.close(),this.visible=!1;return}this.article.style.animation="fadeOutUp 0.3s forwards",setTimeout(()=>{this.dialog.close(),this.visible=!1},300)}showModal(){if(setTimeout(()=>{this.visible=!0},100),!this.animateInOut){this.dialog.showModal();return}this.article.style.animation="fadeInDown 0.3s forwards",this.dialog.showModal()}connectedCallback(){var a,o;this.closeButton.addEventListener("click",this.closeButtonListener),((a=this.getAttribute("persist"))==null?void 0:a.toLowerCase())!=="true"&&document.documentElement.addEventListener("click",this.noPersistHandler),this.animateInOut=((o=this.getAttribute("animate"))==null?void 0:o.toLowerCase())==="true",this.eventData=this.getAttribute("event-data")??null}disconnectedCallback(){this.closeButton.removeEventListener("click",this.closeButtonListener)}attributeChangedCallback(t,a,o){switch(t){case"animate":this.animateInOut=o.toLowerCase()==="true";break;case"persist":const r=o.toLowerCase()==="true";if(document.documentElement.removeEventListener("click",this.noPersistHandler),r)return;document.documentElement.addEventListener("click",this.noPersistHandler);break;case"event-data":this.eventData=o;break;case"title":this.titleSlotElement.textContent=o;break}}static register(){customElements.define("form-modal",l,{extends:"dialog"})}}l.register();const n=document.getElementById("create-invitation-button");n&&n.addEventListener("click",i=>{i.preventDefault();const s=document.querySelector("form-modal"),t=s.querySelector("#email");s.showModal(),setTimeout(()=>{t.focus()},50)});
