// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Account        string
	AuthProvider   string
	File           string
	FileGroup      string
	FilePassword   string
	GorpMigrations string
	Invitation     string
	Session        string
}{
	Account:        "account",
	AuthProvider:   "auth_provider",
	File:           "file",
	FileGroup:      "file_group",
	FilePassword:   "file_password",
	GorpMigrations: "gorp_migrations",
	Invitation:     "invitation",
	Session:        "session",
}
